---
- name: Configure etcd
  become: yes
  hosts: all
  tasks:
    # - name: Display all variables/facts known for a host
    #   ansible.builtin.debug:
    #     var: hostvars

    - name: Copying scripts to remote
      become: true 
      copy:
        src: scripts
        dest: /home/vagrant/
        mode: 0550

    - name: Ensure that etcd is present
      yum:
        name: etcd
        state: present

    - name: Ensure that etcd is properly configured
      template:
        src: etcd.conf
        dest: /etc/etcd/etcd.conf

    - name: Ensure etcd is running
      service:
        name: etcd
        state: started
        enabled: True

    - name: Run etcd.sh
      shell:
         "./scripts/etcd.sh {% for host in groups['all'] %}{{ hostvars[host]['ansible_eth1']['ipv4']['address'] }} {% endfor %}"
