---
- name: Configure etcd
  become: yes
  hosts: all
  tasks:
    - name: Ensure that etcd is present
      yum:
        name: etcd
        state: present

    - name: Ensure that etcd is properly configured
      template:
        src: etcd.conf
        dest: /etc/etcd/etcd.conf

    - name: Ensure etcd is running
      service:
        name: etcd
        state: started
        enabled: True
